#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\HomeController::index

sobre:
    path: /sobre
    controller: App\Controller\HomeController::sobre

#Usuário-----
usuario:
    path: /usuario
    controller: App\Controller\Usuario\UsuarioController::usuario
    methods: GET|POST

cadastrarUsuario:
    path: /usuario/cadastrar
    controller: App\Controller\Usuario\CadastrarUsuarioController::cadastrarUsuario
    methods: GET|POST

logarNoSistema:
    path: /usuario/login
    controller: App\Controller\Usuario\UsuarioController::loginUsuario
    methods: GET|POST

usuarioIndex:
    path: /usuario/index
    controller: App\Controller\Usuario\UsuarioController::index
    methods: GET|POST

servicos:
    path: /servicos/index
    controller: App\Controller\Servico\ServicoController::index
    methods: GET|POST

#Cooperado-----
cooperado:
    path: /cooperado
    controller: App\Controller\Cooperado\CooperadoController::cooperado
    methods: GET|POST

cadastrarCooperado:
    path: /cooperado/cadastrar
    controller: App\Controller\Cooperado\CooperadoController::cadastrar
    methods: GET

cooperados:
    path: /cooperado/lista
    controller: App\Controller\Cooperado\CooperadoController::listar
    methods: GET|POST

salvarCooperado:
    path: /cooperado/salvar
    controller: App\Controller\Cooperado\SalvarCooperadoController::salvar
    methods: POST

cadastroRealizado:
    path: /cooperado/teste
    controller: App\Controller\Cooperado\CooperadoController::cadastrado
    methods: GET|POST

cooperadoDesligado:
    path: /cooperado/desligados
    controller: App\Controller\Cooperado\CooperadoController::desligados
    methods: GET|POST

novasMatriculas:
    path: /cooperado/novos
    controller: App\Controller\Cooperado\CooperadoController::novos
    methods: GET|POST

efetivarMatricula:
    path: /cooperado/efetivar
    controller: App\Controller\Cooperado\CooperadoController::efetivar
    methods: GET|POST

desligarMatricula:
    path: /cooperado/desligar
    controller: App\Controller\Cooperado\CooperadoController::desligar
    methods: GET|POST

#Curso-----
curso:
    path: /curso
    controller: App\Controller\Curso\CursoController::curso
    methods: GET

cadastrarCurso:
    path: /curso/cadastrar
    controller: App\Controller\Curso\CursoController::cadastrar
    methods: GET|POST

salvarCurso:
    path: /curso/salvar
    controller: App\Controller\Curso\SalvarCursoController::salvar
    methods: GET|POST

editarCurso:
    path: /curso/editar
    controller: App\Controller\Curso\CursoController::editar
    methods: GET|POST

#Serviço-----
servico:
    path: /servico
    controller: App\Controller\Servico\ServicoController::servico
    methods: GET|POST