#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\HomeController::index

#Usuário-----
usuario:
    path: /usuario
    controller: App\Controller\Usuario\UsuarioController::usuario
    methods: GET|POST

cadastrarUsuario:
    path: /usuario/cadastrar
    controller: App\Controller\Usuario\CadastrarUsuarioController::cadastrarUsuario
    methods: GET|POST

logarNoSistema:
    path: /usuario/login
    controller: App\Controller\Usuario\UsuarioController::loginUsuario
    methods: GET|POST

#Cooperado-----
cooperado:
    path: /cooperado
    controller: App\Controller\Cooperado\CooperadoController::cooperado
    methods: GET|POST

cadastrarCooperado:
    path: /cooperado/cadastrar
    controller: App\Controller\Cooperado\CooperadoController::cadastrar
    methods: GET

salvarCooperado:
    path: /cooperado/salvar
    controller: App\Controller\Cooperado\SalvarCooperadoController::salvar
    methods: POST

cadastroRealizado:
    path: /cooperado/teste
    controller: App\Controller\Cooperado\CooperadoController::cadastrado
    methods: GET|POST

cooperadoDesligado:
    path: /cooperado/desligados
    controller: App\Controller\Cooperado\CooperadoController::desligados
    methods: GET|POST

novasMatriculas:
    path: /cooperado/novos
    controller: App\Controller\Cooperado\CooperadoController::novos
    methods: GET|POST

#Curso-----
curso:
    path: /curso
    controller: App\Controller\Curso\CursoController::curso
    methods: GET|POST

cadastrarCurso:
    path: /curso/cadastrar
    controller: App\Controller\Curso\CursoController::cadastrar
    methods: GET|POST



